### PR TITLE
To-Do Development

### PR DESCRIPTION
**Pull request by XolaniMba**

### CODE REVIEW

**Review by ManeoMalatsi — COMMENTED** [review]
please add a readme file

**Comment by XolaniMba** [comment]
> please add a readme file

okay thanks i will do so

**Review by NthabisengLekolwana — COMMENTED** [review]
Add the title on your To-Do List

**Comment by XolaniMba** [comment]
> Add the title on your To-Do List

thanks i did

**Review by ManeoMalatsi — APPROVED** [review]

**Pull request merged**
